CREATE TABLE `cms_qiniu_upload_file`
(
    `id`              int(11) unsigned NOT NULL AUTO_INCREMENT,
    `uuid`            varchar(128) NOT NULL DEFAULT '' COMMENT '文件UUID',
    `bucket`          varchar(255) NOT NULL DEFAULT '' COMMENT '所属的bucket',
    `key`             varchar(255) NOT NULL DEFAULT '' COMMENT '资源key',
    `file_name`       varchar(255) NOT NULL DEFAULT '' COMMENT '文件名',
    `file_type`       varchar(255) NOT NULL DEFAULT '' COMMENT '文件mime类型',
    `file_ext`        varchar(16)  NOT NULL DEFAULT '' COMMENT '文件后缀',
    `file_size`       int(11) NOT NULL DEFAULT '0' COMMENT '文件大小，单位byte',
    `file_url`        text NOT NULL COMMENT '文件URL',
    `create_time`     int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
    `update_time`     int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
    `download_amount` int(11) NOT NULL DEFAULT '0' COMMENT '下载次数',
    `view_amount`     int(11) NOT NULL DEFAULT '0' COMMENT '浏览次数',
    `file_status`     tinyint(1) NOT NULL DEFAULT '0' COMMENT '文件状态 0正常，启用 1禁用',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uuid` (`uuid`),
    KEY               `bucket` (`bucket`(191),`key`(191)),
    KEY               `create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cms_qiniu_fetch_file`
(
    `id`              int(11) unsigned NOT NULL AUTO_INCREMENT,
    `uuid`            varchar(128) NOT NULL DEFAULT '' COMMENT '文件UUID',
    `bucket`          varchar(255) NOT NULL DEFAULT '' COMMENT '所属的bucket',
    `key`             varchar(255) NOT NULL DEFAULT '' COMMENT '资源key',
    `file_name`       varchar(255) NOT NULL DEFAULT '' COMMENT '文件名',
    `file_type`       varchar(255) NOT NULL DEFAULT '' COMMENT '文件mime类型',
    `file_ext`        varchar(16)  NOT NULL DEFAULT '' COMMENT '文件后缀',
    `file_size`       int(11) NOT NULL DEFAULT '0' COMMENT '文件大小，单位byte',
    `file_url`        text NOT NULL COMMENT '文件URL',
    `create_time`     int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
    `update_time`     int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
    `download_amount` int(11) NOT NULL DEFAULT '0' COMMENT '下载次数',
    `view_amount`     int(11) NOT NULL DEFAULT '0' COMMENT '浏览次数',
    `file_status`     tinyint(1) NOT NULL DEFAULT '0' COMMENT '文件状态 0正常，启用 1禁用',
    `fetch_status`    tinyint(1) NOT NULL DEFAULT '0' COMMENT '拉取状态0拉取中，1拉取完成2拉取失败',
    `fetch_task_id` varchar(512) NOT NULL DEFAULT '' COMMENT '七牛异步任务ID，历史记录为空',
    `fetch_wait` int NOT NULL DEFAULT '0' COMMENT '七牛异步抓取排队数：大于0为前方排队任务数，0为当前任务正在处理，-1为任务至少已处理过一次且可能进入重试，不代表成功或失败',
    `fetch_error` varchar(1000) NOT NULL DEFAULT '' COMMENT '脱敏抓取失败或请求异常原因',
    `submitted_at` int NOT NULL DEFAULT '0' COMMENT '最近提交时间戳',
    `callback_hash` char(64) NOT NULL DEFAULT '' COMMENT '当前尝试回调凭证SHA256',
    `fetch_url`       text COMMENT '抓取的url',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uuid` (`uuid`),
    KEY               `bucket` (`bucket`(191),`key`(191)),
    KEY               `create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
